algoritmo "questao_2"
// Função : Peça para o usuário digitar um valor informe se ele é par ou ímpar
// Autor :  Bianca Prado
// Data : 07/08/2022
// Seção de Declarações 
var
num:inteiro

inicio
// Seção de Comandos
escreval("Digite um número: ")
leia(num)

se(num mod 2=0) entao
   escreval("O número",num," é par!")
senao
     escreval("O número",num,"é ímpar!")
FIMSE


fimalgoritmo
